import { describe, expect, it } from "vitest";
import type { CommandsData } from "../../../src/cli/commands/commands.js";
import { generateBashCompletions, generateFishCompletions, generateZshCompletions } from "../../../src/cli/commands/completions.js";

const mockInventory: CommandsData = {
	version: "0.1.0",
	groups: [
		{
			name: "debug",
			description: "Debug commands",
			commands: [
				{
					name: "launch",
					description: "Launch a debug session",
					group: "debug",
					args: [
						{ name: "program", type: "positional", required: true, description: "Program to debug" },
						{ name: "json", type: "boolean", required: false, description: "Output as JSON", default: false },
						{ name: "language", type: "string", required: false, description: "Language" },
					],
				},
				{ name: "stop", description: "Stop a session", group: "debug", args: [] },
			],
		},
		{
			name: "browser",
			description: "Browser commands",
			commands: [{ name: "start", description: "Start recording", group: "browser", args: [] }],
		},
		{
			name: "top-level",
			description: "Top-level commands",
			commands: [
				{ name: "doctor", description: "Check installed debuggers", group: "top-level", args: [] },
				{ name: "commands", description: "List all commands", group: "top-level", args: [] },
			],
		},
	],
};

describe("bash completions", () => {
	it("includes compgen and complete -F _krometrail", () => {
		const output = generateBashCompletions(mockInventory);
		expect(output).toContain("compgen -W");
		expect(output).toContain("complete -F _krometrail krometrail");
	});

	it("includes _krometrail function definition", () => {
		const output = generateBashCompletions(mockInventory);
		expect(output).toContain("_krometrail()");
	});

	it("includes top-level commands", () => {
		const output = generateBashCompletions(mockInventory);
		expect(output).toContain("debug");
		expect(output).toContain("browser");
		expect(output).toContain("doctor");
		expect(output).toContain("commands");
		expect(output).toContain("completions");
	});

	it("includes global flags", () => {
		const output = generateBashCompletions(mockInventory);
		expect(output).toContain("--help");
		expect(output).toContain("--version");
		expect(output).toContain("--mcp");
	});

	it("includes debug subcommands", () => {
		const output = generateBashCompletions(mockInventory);
		expect(output).toContain("launch");
		expect(output).toContain("stop");
	});

	it("includes --flags for subcommands", () => {
		const output = generateBashCompletions(mockInventory);
		expect(output).toContain("--json");
		expect(output).toContain("--language");
	});

	it("includes bash/zsh/fish as completions subcommand options", () => {
		const output = generateBashCompletions(mockInventory);
		expect(output).toContain("bash");
		expect(output).toContain("zsh");
		expect(output).toContain("fish");
	});

	it("includes a header comment with install instructions", () => {
		const output = generateBashCompletions(mockInventory);
		expect(output).toContain("Installation");
		expect(output).toContain("Generated by");
	});
});

describe("zsh completions", () => {
	it("includes compdef _krometrail krometrail", () => {
		const output = generateZshCompletions(mockInventory);
		expect(output).toContain("compdef _krometrail krometrail");
	});

	it("includes _arguments", () => {
		const output = generateZshCompletions(mockInventory);
		expect(output).toContain("_arguments");
	});

	it("includes _krometrail function definition", () => {
		const output = generateZshCompletions(mockInventory);
		expect(output).toContain("_krometrail()");
	});

	it("includes top-level commands", () => {
		const output = generateZshCompletions(mockInventory);
		expect(output).toContain("debug");
		expect(output).toContain("browser");
		expect(output).toContain("doctor");
		expect(output).toContain("completions");
	});

	it("includes descriptions for commands", () => {
		const output = generateZshCompletions(mockInventory);
		expect(output).toContain("Debug commands");
		expect(output).toContain("Launch a debug session");
	});

	it("includes --flags from inventory", () => {
		const output = generateZshCompletions(mockInventory);
		expect(output).toContain("--json");
		expect(output).toContain("--language");
	});

	it("includes _describe calls", () => {
		const output = generateZshCompletions(mockInventory);
		expect(output).toContain("_describe");
	});

	it("includes a header comment with install instructions", () => {
		const output = generateZshCompletions(mockInventory);
		expect(output).toContain("Installation");
		expect(output).toContain("Generated by");
	});
});

describe("fish completions", () => {
	it("includes complete -c krometrail commands", () => {
		const output = generateFishCompletions(mockInventory);
		expect(output).toContain("complete -c krometrail");
	});

	it("includes __fish_use_subcommand for top-level commands", () => {
		const output = generateFishCompletions(mockInventory);
		expect(output).toContain("__fish_use_subcommand");
	});

	it("includes __fish_seen_subcommand_from for subcommands", () => {
		const output = generateFishCompletions(mockInventory);
		expect(output).toContain("__fish_seen_subcommand_from");
	});

	it("includes top-level commands", () => {
		const output = generateFishCompletions(mockInventory);
		expect(output).toContain("debug");
		expect(output).toContain("browser");
		expect(output).toContain("doctor");
		expect(output).toContain("completions");
	});

	it("includes debug subcommands", () => {
		const output = generateFishCompletions(mockInventory);
		expect(output).toContain("launch");
		expect(output).toContain("stop");
	});

	it("includes -d description for completions", () => {
		const output = generateFishCompletions(mockInventory);
		expect(output).toContain("-d '");
	});

	it("includes flags from inventory", () => {
		const output = generateFishCompletions(mockInventory);
		// fish uses -l 'flagname' syntax rather than --flagname
		expect(output).toContain("-l 'json'");
		expect(output).toContain("-l 'language'");
	});

	it("includes bash/zsh/fish as completions subcommand options", () => {
		const output = generateFishCompletions(mockInventory);
		expect(output).toContain("__fish_seen_subcommand_from completions");
	});

	it("includes a header comment with install instructions", () => {
		const output = generateFishCompletions(mockInventory);
		expect(output).toContain("Installation");
		expect(output).toContain("Generated by");
	});
});
