import { defineCommand } from "citty";
import { buildCommandInventory, type CommandsData } from "./commands.js";

/**
 * Generate a bash completion script from the command inventory.
 */
export function generateBashCompletions(inventory: CommandsData): string {
	const topLevelCmds = inventory.groups.flatMap((g) => g.commands.map((c) => c.name));
	const allTopLevel = [...new Set([...topLevelCmds, "doctor", "commands", "completions"])];

	// Build subcommand lists per group
	const groupSubcmds: Record<string, string[]> = {};
	for (const group of inventory.groups) {
		if (group.name !== "top-level") {
			groupSubcmds[group.name] = group.commands.map((c) => c.name);
		}
	}
	groupSubcmds.completions = ["bash", "zsh", "fish"];

	// Build flag lists per command (group + subcommand key)
	const cmdFlags: Record<string, string[]> = {};
	for (const group of inventory.groups) {
		for (const cmd of group.commands) {
			const flags = cmd.args.filter((a) => a.type !== "positional").map((a) => `--${a.name}`);
			const key = group.name === "top-level" ? cmd.name : `${group.name}_${cmd.name}`;
			cmdFlags[key] = flags;
		}
	}

	const groupSubcmdsCode = Object.entries(groupSubcmds)
		.map(([grp, cmds]) => `\t\t\t${grp}) COMPREPLY=($(compgen -W "${cmds.join(" ")}" -- "$cur")) ;;`)
		.join("\n");

	const flagsCode = Object.entries(cmdFlags)
		.map(([key, flags]) => `\t\t\t${key}) COMPREPLY=($(compgen -W "${flags.join(" ")}" -- "$cur")) ;;`)
		.join("\n");

	const allTopLevelStr = [...allTopLevel, "--mcp", "--tools", "--help", "--version"].join(" ");

	// Build the script using array join to avoid Biome misinterpreting bash variable
	// syntax like ${COMP_WORDS[@]} as JS template expressions.
	const lines = [
		"#!/usr/bin/env bash",
		"# krometrail bash completion script",
		"# Generated by: krometrail completions bash",
		`# Version: ${inventory.version}`,
		"#",
		"# Installation:",
		"#   # One-time:",
		"#   krometrail completions bash > ~/.bash_completion.d/krometrail",
		"#   source ~/.bash_completion.d/krometrail",
		"#",
		"#   # Permanent (add to ~/.bashrc):",
		"#   source <(krometrail completions bash)",
		"",
		"_krometrail() {",
		"\tlocal cur prev words cword",
		"\t_init_completion 2>/dev/null || {",
		'\t\twords=("${COMP_WORDS[@]}")',
		"\t\tcword=$COMP_CWORD",
		'\t\tcur="${COMP_WORDS[COMP_CWORD]}"',
		'\t\tprev="${COMP_WORDS[COMP_CWORD-1]}"',
		"\t}",
		"",
		"\tif [[ $cword -eq 1 ]]; then",
		`\t\tCOMPREPLY=($(compgen -W "${allTopLevelStr}" -- "$cur"))`,
		"\t\treturn 0",
		"\tfi",
		"",
		'\tlocal cmd="${words[1]}"',
		"",
		"\tif [[ $cword -eq 2 ]]; then",
		'\t\tcase "$cmd" in',
		groupSubcmdsCode,
		"\t\t\t*) COMPREPLY=() ;;",
		"\t\tesac",
		"\t\treturn 0",
		"\tfi",
		"",
		"\t# Position 3+: flags for resolved subcommand",
		'\tlocal subcmd="${words[2]}"',
		'\tcase "${cmd}_${subcmd}" in',
		flagsCode,
		"\t\t*) COMPREPLY=() ;;",
		"\tesac",
		"}",
		"",
		"complete -F _krometrail krometrail",
		"",
	];

	return lines.join("\n");
}

/**
 * Generate a zsh completion script from the command inventory.
 */
export function generateZshCompletions(inventory: CommandsData): string {
	// Build subcommand spec lists per group
	const groupSubcmdSpecs: Record<string, string[]> = {};
	for (const group of inventory.groups) {
		if (group.name !== "top-level") {
			groupSubcmdSpecs[group.name] = group.commands.map((c) => `'${c.name}[${c.description.replace(/'/g, "")}]'`);
		}
	}
	groupSubcmdSpecs.completions = ["'bash[Generate bash completions]'", "'zsh[Generate zsh completions]'", "'fish[Generate fish completions]'"];

	// Build flag specs per command
	const cmdFlagSpecs: Record<string, string[]> = {};
	for (const group of inventory.groups) {
		for (const cmd of group.commands) {
			const flagSpecs = cmd.args
				.filter((a) => a.type !== "positional")
				.map((a) => {
					const desc = a.description.replace(/'/g, "").replace(/\[/g, "").replace(/\]/g, "");
					return `'--${a.name}[${desc}]'`;
				});
			const key = group.name === "top-level" ? cmd.name : `${group.name}_${cmd.name}`;
			cmdFlagSpecs[key] = flagSpecs;
		}
	}

	const subFunctions = Object.entries(groupSubcmdSpecs)
		.map(([grp, specs]) => {
			return `_krometrail_${grp}() {\n\tlocal subcmds\n\tsubcmds=(\n\t\t${specs.join("\n\t\t")}\n\t)\n\t_describe '${grp} subcommands' subcmds\n}`;
		})
		.join("\n\n");

	const topLevelSpecs = inventory.groups.filter((g) => g.name !== "top-level").map((g) => `'${g.name}[${g.description.replace(/'/g, "")}]'`);
	topLevelSpecs.push("'doctor[Check installed debuggers]'");
	topLevelSpecs.push("'commands[List all available commands]'");
	topLevelSpecs.push("'completions[Output shell completion script]'");

	const caseDispatch = inventory.groups
		.filter((g) => g.name !== "top-level")
		.map((g) => `\t\t${g.name}) _krometrail_${g.name} ;;`)
		.join("\n");
	const completionsCaseDispatch = "\t\tcompletions) _krometrail_completions ;;";

	// Group the flag cases by group
	const flagCasesByGroup: Record<string, string[]> = {};
	for (const group of inventory.groups) {
		if (group.name === "top-level") continue;
		const cases = group.commands
			.map((cmd) => {
				const key = `${group.name}_${cmd.name}`;
				const specs = cmdFlagSpecs[key] ?? [];
				if (specs.length === 0) return null;
				return `\t\t\t${cmd.name}) _arguments ${specs.join(" ")} ;;`;
			})
			.filter(Boolean);
		if (cases.length > 0) {
			flagCasesByGroup[group.name] = cases as string[];
		}
	}

	const flagDispatch = Object.entries(flagCasesByGroup)
		.map(([grp, cases]) => `\t\t${grp})\n\t\t\tcase "$words[3]" in\n${cases.join("\n")}\n\t\t\tesac\n\t\t\t;;`)
		.join("\n");

	return [
		"#compdef krometrail",
		"# krometrail zsh completion script",
		"# Generated by: krometrail completions zsh",
		`# Version: ${inventory.version}`,
		"#",
		"# Installation:",
		"#   # One-time (add to a directory in your fpath):",
		"#   krometrail completions zsh > ~/.zsh/completions/_krometrail",
		"#",
		"#   # Or add to ~/.zshrc:",
		"#   source <(krometrail completions zsh)",
		"",
		subFunctions,
		"",
		"_krometrail() {",
		"\tlocal state",
		"",
		"\t_arguments \\",
		"\t\t'--mcp[Start as MCP server on stdio]' \\",
		"\t\t'--tools=[Comma-separated tool groups]:tools:(debug browser)' \\",
		"\t\t'--help[Show help]' \\",
		"\t\t'--version[Show version]' \\",
		"\t\t'1: :->cmd' \\",
		"\t\t'*: :->args'",
		"",
		"\tcase $state in",
		"\t\tcmd)",
		"\t\t\tlocal cmds",
		"\t\t\tcmds=(",
		`\t\t\t\t${topLevelSpecs.join("\n\t\t\t\t")}`,
		"\t\t\t)",
		"\t\t\t_describe 'commands' cmds",
		"\t\t\t;;",
		"\t\targs)",
		'\t\t\tcase "$words[2]" in',
		caseDispatch,
		completionsCaseDispatch,
		"\t\t\t\t*)",
		'\t\t\t\t\tcase "$words[2]" in',
		flagDispatch,
		"\t\t\t\t\tesac",
		"\t\t\t\t\t;;",
		"\t\t\tesac",
		"\t\t\t;;",
		"\tesac",
		"}",
		"",
		"compdef _krometrail krometrail",
		"",
	].join("\n");
}

/**
 * Generate a fish completion script from the command inventory.
 */
export function generateFishCompletions(inventory: CommandsData): string {
	const lines: string[] = [
		"#!/usr/bin/env fish",
		"# krometrail fish completion script",
		"# Generated by: krometrail completions fish",
		`# Version: ${inventory.version}`,
		"#",
		"# Installation:",
		"#   krometrail completions fish > ~/.config/fish/completions/krometrail.fish",
		"",
		"# Disable file completions by default",
		"complete -c krometrail -f",
		"",
		"# Global flags",
		"complete -c krometrail -n '__fish_use_subcommand' -l mcp -d 'Start as MCP server on stdio'",
		"complete -c krometrail -n '__fish_use_subcommand' -l tools -d 'Comma-separated tool groups (debug, browser)'",
		"complete -c krometrail -n '__fish_use_subcommand' -s h -l help -d 'Show help'",
		"complete -c krometrail -n '__fish_use_subcommand' -l version -d 'Show version'",
		"",
		"# Top-level commands",
	];

	// Add top-level commands
	for (const group of inventory.groups) {
		if (group.name === "top-level") {
			for (const cmd of group.commands) {
				lines.push(`complete -c krometrail -n '__fish_use_subcommand' -a '${cmd.name}' -d '${cmd.description.replace(/'/g, "")}'`);
			}
		} else {
			lines.push(`complete -c krometrail -n '__fish_use_subcommand' -a '${group.name}' -d '${group.description.replace(/'/g, "")}'`);
		}
	}
	lines.push("complete -c krometrail -n '__fish_use_subcommand' -a 'completions' -d 'Output shell completion script for bash, zsh, or fish'");

	// Add completions subcommand shells
	lines.push("");
	lines.push("# completions subcommand shells");
	for (const shell of ["bash", "zsh", "fish"]) {
		lines.push(`complete -c krometrail -n '__fish_seen_subcommand_from completions' -a '${shell}' -d 'Generate ${shell} completions'`);
	}

	// Add subcommands for each group
	for (const group of inventory.groups) {
		if (group.name === "top-level") continue;
		lines.push("");
		lines.push(`# ${group.name} subcommands`);
		for (const cmd of group.commands) {
			lines.push(`complete -c krometrail -n '__fish_seen_subcommand_from ${group.name}' -a '${cmd.name}' -d '${cmd.description.replace(/'/g, "")}'`);
		}

		// Add flags for each subcommand
		for (const cmd of group.commands) {
			const flags = cmd.args.filter((a) => a.type !== "positional");
			if (flags.length === 0) continue;
			lines.push(`# ${group.name} ${cmd.name} flags`);
			for (const flag of flags) {
				const desc = flag.description.replace(/'/g, "");
				lines.push(`complete -c krometrail -n '__fish_seen_subcommand_from ${cmd.name}' -l '${flag.name}' -d '${desc}'`);
			}
		}
	}

	// Add top-level command flags
	for (const group of inventory.groups) {
		if (group.name !== "top-level") continue;
		for (const cmd of group.commands) {
			const flags = cmd.args.filter((a) => a.type !== "positional");
			if (flags.length === 0) continue;
			lines.push("");
			lines.push(`# ${cmd.name} flags`);
			for (const flag of flags) {
				const desc = flag.description.replace(/'/g, "");
				lines.push(`complete -c krometrail -n '__fish_seen_subcommand_from ${cmd.name}' -l '${flag.name}' -d '${desc}'`);
			}
		}
	}

	return `${lines.join("\n")}\n`;
}

export const completionsCommand = defineCommand({
	meta: {
		name: "completions",
		description: "Output shell completion script for bash, zsh, or fish",
	},
	args: {
		shell: {
			type: "positional",
			description: "Shell to generate completions for: bash, zsh, or fish",
			required: true,
		},
	},
	async run({ args }) {
		const shell = args.shell;
		if (!["bash", "zsh", "fish"].includes(shell)) {
			process.stderr.write(`Unknown shell: ${shell}. Supported: bash, zsh, fish\n`);
			process.exit(2);
		}

		const inventory = await buildCommandInventory();

		const generators: Record<string, (inv: CommandsData) => string> = {
			bash: generateBashCompletions,
			zsh: generateZshCompletions,
			fish: generateFishCompletions,
		};

		process.stdout.write(generators[shell](inventory));
	},
});
